# permissions for end users to view nextflowlaunches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nextflowlaunch-viewer-role
rules:
- apiGroups:
  - batch.mnm.bio
  resources:
  - nextflowlaunches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.mnm.bio
  resources:
  - nextflowlaunches/status
  verbs:
  - get
