apiVersion: v2
name: nextflow-k8s-operator
description: A Helm chart for Kubernetes contains nextflow-operator
type: application
version: 1.2.0
appVersion: "1.2.0"
icon: https://raw.githubusercontent.com/MNMdiagnostics/nextflow-k8s-operator/master/docs/neko_logo.png
